<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Invoice</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 700px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .invoice-container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 40px;
            margin: 20px 0;
        }
        .invoice-header {
            text-align: center;
            border-bottom: 3px solid #007bff;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .invoice-header h1 {
            color: #007bff;
            margin: 0;
            font-size: 28px;
            font-weight: 600;
        }
        .invoice-header p {
            color: #666;
            margin: 5px 0 0 0;
            font-size: 14px;
        }
        .invoice-info {
            margin-bottom: 30px;
        }
        .info-section {
            margin-bottom: 25px;
        }
        .info-section h2 {
            color: #333;
            font-size: 18px;
            margin: 0 0 10px 0;
            padding-bottom: 8px;
            border-bottom: 2px solid #e0e0e0;
        }
        .info-row {
            display: flex;
            margin-bottom: 8px;
            padding: 8px 0;
        }
        .info-label {
            font-weight: 600;
            color: #555;
            width: 180px;
            flex-shrink: 0;
        }
        .info-value {
            color: #333;
            flex: 1;
        }
        .cost-section {
            background-color: #f8f9fa;
            border-left: 4px solid #007bff;
            padding: 20px;
            margin: 30px 0;
            border-radius: 4px;
        }
        .cost-item {
            display: flex;
            justify-content: space-between;
            padding: 12px 0;
            border-bottom: 1px solid #e0e0e0;
        }
        .cost-item:last-child {
            border-bottom: none;
        }
        .cost-label {
            font-weight: 500;
            color: #555;
        }
        .cost-value {
            font-weight: 600;
            color: #007bff;
            font-size: 16px;
        }
        .total-cost {
            margin-top: 15px;
            padding-top: 15px;
            border-top: 2px solid #007bff;
        }
        .total-cost .cost-label {
            font-size: 18px;
            color: #333;
        }
        .total-cost .cost-value {
            font-size: 24px;
            color: #007bff;
        }
        .disclaimer {
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 30px 0;
            border-radius: 4px;
            font-size: 13px;
            color: #856404;
            line-height: 1.8;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            color: #666;
            font-size: 12px;
        }
        .auto-generated {
            color: #999;
            font-size: 11px;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="invoice-container">
        <div class="invoice-header">
            <h1>BOOKING INVOICE</h1>
            <p>Auto-generated by LFG</p>
        </div>

        <div class="invoice-info">
            <div class="info-section">
                <h2>Venue Information</h2>
                <div class="info-row">
                    <span class="info-label">Venue:</span>
                    <span class="info-value">{{ $booking->venue->name }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Address:</span>
                    <span class="info-value">{{ $booking->venue->address }}</span>
                </div>
                @if($booking->event)
                <div class="info-row">
                    <span class="info-label">Event:</span>
                    <span class="info-value">{{ $booking->event->name }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Date:</span>
                    <span class="info-value">{{ \Carbon\Carbon::parse($booking->event->date)->format('F d, Y') }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time:</span>
                    <span class="info-value">{{ \Carbon\Carbon::parse($booking->event->start_time)->format('g:i A') }} - {{ \Carbon\Carbon::parse($booking->event->end_time)->format('g:i A') }}</span>
                </div>
                @endif
            </div>
        </div>

        <div class="cost-section">
            <div class="cost-item">
                <span class="cost-label">Total Cost</span>
                <span class="cost-value">₱{{ number_format($totalCost, 2) }}</span>
            </div>
            <div class="cost-item">
                <span class="cost-label">Cost per slot (if full)</span>
                <span class="cost-value">₱{{ number_format($costPerSlotIfFull, 2) }}</span>
            </div>
            <div class="cost-item total-cost">
                <span class="cost-label">Cost per slot (current) ({{ $participantsCount }} participant{{ $participantsCount != 1 ? 's' : '' }})</span>
                <span class="cost-value">₱{{ number_format($costPerSlotCurrent, 2) }}</span>
            </div>
        </div>

        <div class="disclaimer">
            <strong>Disclaimer:</strong> LFG does not handle venue to player payment processes. Please coordinate directly with the venue for payment arrangements. Please pay responsibly and ensure all transactions are completed in a timely manner.
        </div>

        <div class="footer">
            <p>This is an automated invoice generated by LFG (Looking For Game)</p>
            <p class="auto-generated">Auto-generated invoice - Please do not reply to this email</p>
        </div>
    </div>
</body>
</html>
